### PR TITLE
Update README for RSA PrivKey Formatting

### PR DESCRIPTION
**Pull request by MNThomson**
Thank you so much for a great template repo for creating Github Apps!

The formatting in the README was not showing a nicely formatted Github Private Key. Changing the README to a markdown file solved this issue.

### CODE REVIEW

**Comment by Mariatta** [comment]
Thanks for noticing the problem with the text formatting on the readme file. However it's not necessary to convert it into Markdown.

ReStructuredText supports literal text block, as defined here: https://docutils.sourceforge.io/docs/user/rst/quickref.html#literal-blocks

So we just need to convert the syntax from

```
```
Text
```
```

Into 

```
::

    Text
    
```

**Review by Mariatta — CHANGES_REQUESTED** [review]
Please keep the file in rst, but use the literal block syntax. https://docutils.sourceforge.io/docs/user/rst/quickref.html#literal-blocks

**Comment by MNThomson** [comment]
Noticed that `rst` had literal blocks a few minutes after I submitted this PR.
Everything should be good to go now!

**Review by Mariatta — APPROVED** [review]
Thanks!

**Pull request merged**
